# Generated by Django 5.2.5 on 2025-08-09 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("livros", "0001_initial"),
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotaDeLeitura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comentario", models.TextField(verbose_name="Comentário")),
                (
                    "data",
                    models.DateField(auto_now_add=True, verbose_name="Data da Nota"),
                ),
                (
                    "livro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notas",
                        to="livros.livro",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notas_de_leitura",
                        to="usuarios.perfilusuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nota de Leitura",
                "verbose_name_plural": "Notas de Leitura",
                "unique_together": {("livro", "usuario")},
            },
        ),
    ]
