# Generated by Django 4.2.19 on 2025-09-03 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_perfilusuario_biografia_and_more'),
        ('notas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notadeleitura',
            options={'ordering': ['-likes', '-data'], 'verbose_name': 'Nota de Leitura', 'verbose_name_plural': 'Notas de Leitura'},
        ),
        migrations.AddField(
            model_name='notadeleitura',
            name='dislikes',
            field=models.PositiveIntegerField(default=0, verbose_name='Não curtidas'),
        ),
        migrations.AddField(
            model_name='notadeleitura',
            name='likes',
            field=models.PositiveIntegerField(default=0, verbose_name='Curtidas'),
        ),
        migrations.CreateModel(
            name='AvaliacaoNota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('like', 'Curtir'), ('dislike', 'Não Curtir')], max_length=7)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='notas.notadeleitura')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_notas', to='usuarios.perfilusuario')),
            ],
            options={
                'verbose_name': 'Avaliação de Nota',
                'verbose_name_plural': 'Avaliações de Notas',
                'unique_together': {('nota', 'usuario')},
            },
        ),
    ]
