# Generated by Django 4.2.19 on 2025-09-03 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0002_alter_notadeleitura_options_notadeleitura_dislikes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notadeleitura',
            options={'verbose_name': 'Nota de Leitura', 'verbose_name_plural': 'Notas de Leitura'},
        ),
        migrations.RemoveField(
            model_name='notadeleitura',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='notadeleitura',
            name='likes',
        ),
        migrations.DeleteModel(
            name='AvaliacaoNota',
        ),
    ]
