# Generated by Django 5.2.6 on 2025-09-06 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notas", "0003_alter_notadeleitura_options_and_more"),
        ("usuarios", "0003_usuario_remove_perfilusuario_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notadeleitura",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notas_de_leitura",
                to="usuarios.usuario",
            ),
        ),
    ]
