# Generated by Django 4.2.19 on 2025-09-03 01:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('generos', '0001_initial'),
        ('autores', '0002_autor_biografia_alter_autor_pais'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'ordering': ['nome'], 'verbose_name': 'Autor', 'verbose_name_plural': 'Autores'},
        ),
        migrations.AddField(
            model_name='autor',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='autor',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='autor',
            name='data_falecimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='autor',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='autor',
            name='generos',
            field=models.ManyToManyField(blank=True, related_name='autores', to='generos.genero', verbose_name='Gêneros literários'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='biografia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='autor',
            name='nome',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='autor',
            name='pais',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
