# Generated by Django 5.2.6 on 2025-09-06 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("livros", "0004_alter_livro_usuario"),
        ("notas", "0004_alter_notadeleitura_usuario"),
        ("usuarios", "0003_usuario_remove_perfilusuario_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PerfilUsuario",
        ),
    ]
