# Generated by Django 5.2.5 on 2025-09-06 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("usuarios", "0004_delete_perfilusuario"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="group",
            field=models.ForeignKey(
                blank=True,
                help_text="O grupo a que este usuário pertence. Um usuário terá todas as permissões concedidas a este grupo.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="usuarios",
                related_query_name="usuario",
                to="auth.group",
                verbose_name="grupo",
            ),
        ),
    ]
