# Generated by Django 4.2.19 on 2025-09-03 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generos', '0001_initial'),
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='genero',
        ),
        migrations.AddField(
            model_name='livro',
            name='generos',
            field=models.ManyToManyField(related_name='livros', to='generos.genero'),
        ),
    ]
