# Generated by Django 4.2.19 on 2025-09-03 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generos', '0001_initial'),
        ('livros', '0002_remove_livro_genero_livro_generos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='generos',
        ),
        migrations.AddField(
            model_name='livro',
            name='genero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livros', to='generos.genero'),
        ),
    ]
