# Generated by Django 5.2.6 on 2025-09-06 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livros", "0003_remove_livro_generos_livro_genero"),
        ("usuarios", "0003_usuario_remove_perfilusuario_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livro",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="minha_biblioteca",
                to="usuarios.usuario",
            ),
        ),
    ]
